Repository nextcloud/files_lock, pull requests merged in 2023-12, with the labels that each got.

#188 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#194 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#196 perf: Avoid re-query of already fetched lock info
  lib/Service/LockService.php
Labels: 3. to review, performance 🚀

#201 [stable27] fix: Preserve lock data in file info model
  js/files.js
Labels: bug, 3. to review
