Repository nextcloud/files_lock, pull requests merged in 2024-12, with the labels that each got.

#446 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#450 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#445 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#447 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#448 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#449 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#455 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#462 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#452 fix: Use proper user when unlocking an app locked file with occ
  lib/Service/LockService.php
Labels: bug, 3. to review

#471 fix: Use icons instead of avatar for locking indication
  src/helper.ts
  src/main.ts
Labels: enhancement, 3. to review, design, ux

#464 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#456 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#463 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#480 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#478 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#479 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#477 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#476 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
