Repository nextcloud/files_lock, pull requests merged in 2024-10, with the labels that each got.

#339 chore: Fix indention of composer.json
  composer.json
Labels: 3. to review

#340 test: Add test for extending locks
  tests/Feature/LockFeatureTest.php
  tests/bootstrap.php
Labels: 3. to review, tests

#367 fix(ci): litmus test with current upload-artifact
  .github/workflows/litmus.yml
Labels: backport-request

#357 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#346 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#348 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#351 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#355 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#354 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#344 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#379 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#378 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#377 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#376 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
