Repository nextcloud/files_lock, pull requests merged in 2024-05, with the labels that each got.

#296 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#300 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#294 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#298 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#302 Fix some deprecation warnings
  lib/DAV/LockBackend.php
  lib/DAV/LockPlugin.php
  tests/Feature/LockFeatureTest.php
Labels: 3. to review, technical debt

#304 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#307 fix: Show lock status for read only files and allow unlocking
  js/files.js
Labels: bug, 3. to review

#312 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#311 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#310 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#297 perf(boot): Initialize storage wrapper and lock manager more lazy
  composer.lock
  lib/AppInfo/Application.php
Labels: 3. to review, performance 🚀
