Repository nextcloud/files_lock, pull requests merged in 2024-04, with the labels that each got.

#278 fix/error display name
  lib/Controller/LockController.php
  lib/Service/LockService.php
  lib/Tools/Db/ExtendedQueryBuilder.php
Labels: bug, 3. to review, backport-request

#275 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#273 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#284 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#274 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#288 fix: Only update lock timeout when it is not infinite
  lib/Service/LockService.php
Labels: bug, 3. to review

#286 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
