Repository nextcloud/files_lock, pull requests merged in 2024-02, with the labels that each got.

#231 feat: translate controller status messages
  lib/Controller/LockController.php
Labels: enhancement, 3. to review

#229 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#230 [stable28] chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#232 chore: upgrade phpunit workflows
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
  composer.json
Labels: 3. to review

#227 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#226 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#176 Fix lock state icon position in detailed files' lists
  css/files_lock.css
Labels: files app, feature: locking, 3. to review, design, papercut, feedback-requested
