Repository nextcloud/files_lock, pull requests merged in 2024-03, with the labels that each got.

#248 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#246 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#239 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#234 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#251 fix: Use lock owner display name on error response
  lib/Controller/LockController.php
Labels: bug, 3. to review

#252 fix: Allow to unlock based on the current lock not the requested one to allow lock owners to unlock in any case
  lib/Service/LockService.php
Labels: bug, 3. to review, backport-request

#253 Return proper lock type in webdav response
  lib/DAV/LockPlugin.php
Labels: bug, 3. to review, backport-request

#263 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#262 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#261 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#260 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#256 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies
