Repository nextcloud/files_lock, pull requests merged in 2024-01, with the labels that each got.

#205 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#203 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#204 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#211 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#212 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#199 feat: Add API parameters to specify the lock type
  README.md
  lib/Capability.php
  lib/Controller/LockController.php
  lib/DAV/LockPlugin.php
  lib/Service/LockService.php
Labels: enhancement, 3. to review, backport-request

#219 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#217 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#216 [stable28] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: dependencies, 3. to review

#222 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
