Repository nextcloud/files_lock, pull requests merged in 2025-03, with the labels that each got.

#570 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#573 chore(deps): bump deps of update-nextcloud-ocp-approve-merge
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: 3. to review, technical debt

#583 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#584 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#585 fix/nextcloud ocp approve merge
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: dependencies, 3. to review

#581 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#597 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#595 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#599 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#596 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#598 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#586 fix: Hide empty inline menu entry in grid view
  src/main.ts
  src/styles.css
Labels: bug, 3. to review, backport-request

#614 chore(ci): fix auto merge in ocp workflow
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: 3. to review

#609 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
