Repository nextcloud/files_lock, pull requests merged in 2025-02, with the labels that each got.

#525 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#524 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#521 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#523 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#522 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#528 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#520 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#529 Add playwright skeleton for e2e tests
  .github/workflows/playwright.yml
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  playwright/e2e/viewer.spec.ts
  playwright/start-nextcloud-server.mjs
  playwright/support/fixtures/random-user.ts
  playwright/support/setup.ts
Labels: 3. to review, tests

#497 fix(timeout): compare creation time to now - timeout
  lib/Controller/LockController.php
  lib/Db/LocksRequest.php
  lib/Service/LockService.php
  lib/Tools/Traits/TLogger.php
  tests/Feature/LockFeatureTest.php
Labels: 3. to review

#527 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#551 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#550 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#552 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#548 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#547 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#519 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
